[package]
name = "isopod_derive"
version = "0.1.0"
edition = "2021"

[lib]
name = "isopod_derive"
proc-macro = true

[dependencies]
syn = { version = "2.0.98", features = ["extra-traits"] }
quote = "1.0.38"
proc-macro2 = "1.0.93"